---
server:
  servlet:
    context-path: /treko
  port: 8080

---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: root
    password: root
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
      
---
spring:
  profiles: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false 
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/app_database
    username: postgres
    password: postgres
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl      

# logging hibernate query params 
logging:
  level:
    org: 
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    
trekoo:
  app:
    jwtSecret: jwtTrekooSecretKey
    jwtExpiration: 86400
 
